---
#
# This playbook pings
#
- name: (Play 1) ICMP ping
  hosts: FABRIC
  # https://arista.my.site.com/AristaCommunity/s/article/arista-ansible-getting-started
  # the module is not copied to the Arista switch, rather, it stays on the Ansible Control Host and executes locally.
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    #- arista.eos
  vars:
    #fabric_dir_name: "{{fabric_name}}"
    #execute_tasks: false
    delegate: localhost
  tasks:
    # Check if host is already online.
    # We run 2 pings because the first ping often fails.
    - name: Initial ping...
      delegate_to: "{{ delegate }}"
      #ansible.builtin.shell: ping -c 1 -w 2 "{{ inventory_hostname }}"
      command: ping -c 1 -w 2 "{{ inventory_hostname }}"
      ignore_errors: true
      changed_when: false
      check_mode: false
    
    - name: Print message
      ansible.builtin.debug:
        msg: Hello world
    
    - name: Backup current switch config (eos)
      arista.eos.eos_config:
        backup: yes
      register: backup_eos_location
      when: ansible_network_os == 'arista.eos.eos'

    - name: Gather info from Show Version
      arista.eos.eos_command:
        commands: 'show version'
        #transport: eapi
        #use_ssl: true

- name: Play number TWO
  hosts: SPINES
  connection: local
  gather_facts: false
  #collections:
  #  - arista.avd
  vars:
    #fabric_dir_name: "{{fabric_name}}"
    #execute_tasks: false
    delegate: localhost
  tasks:
    # Check if host is already online.
    # We run 2 pings because the first ping often fails.
    - name: Second ping...
      delegate_to: "{{ delegate }}"
      #ansible.builtin.shell: ping -c 1 -w 2 "{{ inventory_hostname }}"
      command: ping -c 1 -w 2 "{{ inventory_hostname }}"
      ignore_errors: true
      changed_when: false
      check_mode: false
    
    - name: Print message
      ansible.builtin.debug:
        msg: Hello world for second time
