---
# The goal of this test is to verify that node l3_interfaces can generate BGP peerings even if BGP is not required for underlay or overlay.
# The node type *must* have `underlay_router: true` to even be considered an L3 device.
# The uplink type is overridden to `lan` to also ensure that nothing is relying on uplink type p2p / p2p-vrfs.

# l3spine has default overlay and underlay protocols set to none, so it will not have any BGP config by default.
type: l3spine

ipv4_prefix_list_catalog:
  - name: ALLOW-DEFAULT
    sequence_numbers:
      - sequence: 10
        action: permit 0.0.0.0/0

l3spine:
  nodes:
    - name: node-type-l3-interfaces-bgp
      loopback_ipv4_pool: 192.168.255.0/24
      id: 1
      bgp_as: 65000
      uplink_type: lan
      l3_interfaces:
        - # triggering bgp
          name: Ethernet43
          enabled: false
          ip_address: 192.168.42.42/24
          peer_ip: 192.168.42.1
          wan_carrier: INTERNET
          bgp:
            peer_as: 65042
            ipv4_prefix_list_in: ALLOW-DEFAULT
