type: pe

# Testing the deprecated design.type. To be removed in AVD6.0.0.
design:
  type: mpls

pe:
  defaults:
    loopback_ipv4_pool: 10.42.0.0/24
    bgp_as: 42
    id: 42
  nodes:
    - name: host2
      id: 102
      bgp_as: 102
      virtual_router_mac_address: 00:1c:73:00:dc:01
