version: '3.8'

services:
  my_ans:
    image: dl_image_02
    volumes:
    # https://docs.divio.com/en/latest/reference/docker-docker-compose/#:~:text=When%20you%20execute%20a%20docker,overwritten%20by%20the%20mounted%20path.
      - .:/ansible:rw
    command: bash
    tty: true

