---
requires_ansible: '>=2.15.0,<2.19.0'
plugin_routing:
  filter:
    convert_dicts:
      tombstone:
        removal_version: 5.0.0
        warning_text: |-
          The internal 'arista.avd.convert_dicts' filter plugin is no longer used by AVD.
          The plugin is released as open source, so it can be copied and reused according to the license and copyright.
    hash_passphrase:
      tombstone:
        removal_version: 5.0.0
        warning_text: Use arista.avd.snmp_hash instead.
    generate_esi:
      tombstone:
        removal_version: 5.0.0
        warning_text: Use Jinja string concatenation instead like `{{ <esi_prefix> ~ <short_esi> }}`.
    generate_lacp_id:
      tombstone:
        removal_version: 5.0.0
        warning_text: Use the builtin `replace` filter instead like `{{ <short_esi> | replace(':', '.') }}`.
    generate_route_target:
      tombstone:
        removal_version: 5.0.0
        warning_text: >-
          Use the builtin `ansible.builtin.regex_replace` filter instead like
          `{{ <short_esi> | ansible.builtin.regex_replace('(\\d{2})(\\d{2}):(\\d{2})(\\d{2}):(\\d{2})(\\d{2})', '\\1:\\2:\\3:\\4:\\5:\\6') }}`.
  modules:
    _emit_warning:
      tombstone:
        removal_version: 5.0.0
        warning_text: |-
          The internal 'arista.avd._emit_warning' action plugin is not longer used by AVD.
    deploy_to_cv:
      tombstone:
        removal_version: 5.0.0
        warning_text: |-
          The preview module 'arista.avd.deploy_to_cv' has been released under the new name 'arista.avd.cv_workflow'.
    batch_template:
      tombstone:
        removal_version: 5.0.0
        warning_text: |-
          The internal 'arista.avd.batch_template' action plugin is no longer used by AVD.
          The plugin is released as open source, so it can be copied and reused according to the license and copyright.
    validate_and_template:
      tombstone:
        removal_version: 5.0.0
        warning_text: |-
          The internal 'arista.avd.validate_and_template' action plugin is no longer used by AVD.
          The plugin is released as open source, so it can be copied and reused according to the license and copyright.
    yaml_templates_to_facts:
      tombstone:
        removal_version: 5.0.0
        warning_text: |-
          The internal 'arista.avd.yaml_templates_to_facts' action plugin is no longer used by AVD.
          The plugin is released as open source, so it can be copied and reused according to the license and copyright.
  action:
    _emit_warning:
      tombstone:
        removal_version: 5.0.0
        warning_text: |-
          The internal 'arista.avd._emit_warning' action plugin is not longer used by AVD.
    deploy_to_cv:
      tombstone:
        removal_version: 5.0.0
        warning_text: |-
          The preview module 'arista.avd.deploy_to_cv' has been released under the new name 'arista.avd.cv_workflow'.
    batch_template:
      tombstone:
        removal_version: 5.0.0
        warning_text: |-
          The internal 'arista.avd.batch_template' action plugin is no longer used by AVD.
          The plugin is released as open source, so it can be copied and reused according to the license and copyright.
    validate_and_template:
      tombstone:
        removal_version: 5.0.0
        warning_text: |-
          The internal 'arista.avd.validate_and_template' action plugin is no longer used by AVD.
          The plugin is released as open source, so it can be copied and reused according to the license and copyright.
    yaml_templates_to_facts:
      tombstone:
        removal_version: 5.0.0
        warning_text: |-
          The internal 'arista.avd.yaml_templates_to_facts' action plugin is no longer used by AVD.
          The plugin is released as open source, so it can be copied and reused according to the license and copyright.
