router_isis:
  instance: EVPN_UNDERLAY
  mpls_ldp_sync_default: true
  spf_interval:
    interval: 250
    wait_interval: 30
  set_overload_bit:
    enabled: true
    on_startup:
      wait_for_bgp:
        enabled: true
        timeout: 10
  authentication:
    both:
      key_type: 0
      key: password
      mode: shared-secret
      shared_secret:
        profile: test1
        algorithm: md5
      rx_disabled: true
  segment_routing_mpls:
    prefix_segments:
      - prefix: 155.2.1.11/32
