loopback_ipv4_pool: 192.168.1.0/24

type: l2leaf
l2leaf:
  defaults:
  nodes:
    - name: connected-endpoints-monitor-session-network-port-acl
network_ports:
  - switches:
      - connected-endpoints-monitor-session-network-port-acl
    switch_ports:
      - Ethernet24-25
    description: PC
    monitor_sessions:
      - name: DMF
        role: source
        source_settings:
          access_group:
            type: ip
            name: acl2
        session_settings:
          access_group:
            type: ip
            name: acl1

expected_error_message: >-
  Cannot set an ACL for both `session_settings` and `source_settings` under the monitor session 'DMF'
  for network_ports[0].
