fabric_name: FABRIC_INVALID_SCHEMA

type: l2leaf
l2leaf:
  nodes:
    - node: invalid-schema # <--- Key should have been "name"
      id: 1

expected_error_message: >-
  2 errors found during schema validation of input vars.
